// Mocks generated by Mockito 5.4.6 from annotations
// in exam_app/test/feature/Home/data/repo/home_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:exam_app/config/base/base_response.dart' as _i7;
import 'package:exam_app/config/network/safe_call.dart' as _i6;
import 'package:exam_app/feature/Home/data/data_source/remote/home_remote_datasource.dart'
    as _i4;
import 'package:exam_app/feature/Home/data/models/exams_response.dart' as _i3;
import 'package:exam_app/feature/Home/data/models/subjects_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSubjectsResponse_0 extends _i1.SmartFake
    implements _i2.SubjectsResponse {
  _FakeSubjectsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExamsResponse_1 extends _i1.SmartFake implements _i3.ExamsResponse {
  _FakeExamsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDatasource extends _i1.Mock
    implements _i4.HomeRemoteDatasource {
  MockHomeRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SubjectsResponse> getSubjects() =>
      (super.noSuchMethod(
            Invocation.method(#getSubjects, []),
            returnValue: _i5.Future<_i2.SubjectsResponse>.value(
              _FakeSubjectsResponse_0(
                this,
                Invocation.method(#getSubjects, []),
              ),
            ),
          )
          as _i5.Future<_i2.SubjectsResponse>);

  @override
  _i5.Future<_i3.ExamsResponse> getExams(String? subjectId) =>
      (super.noSuchMethod(
            Invocation.method(#getExams, [subjectId]),
            returnValue: _i5.Future<_i3.ExamsResponse>.value(
              _FakeExamsResponse_1(
                this,
                Invocation.method(#getExams, [subjectId]),
              ),
            ),
          )
          as _i5.Future<_i3.ExamsResponse>);
}

/// A class which mocks [SafeCall].
///
/// See the documentation for Mockito's code generation for more information.
class MockSafeCall extends _i1.Mock implements _i6.SafeCall {
  MockSafeCall() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i7.BaseResponse<T>> safeApiCall<T>(
    _i5.Future<T> Function()? apiCall,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#safeApiCall, [apiCall]),
            returnValue: _i5.Future<_i7.BaseResponse<T>>.value(
              _i8.dummyValue<_i7.BaseResponse<T>>(
                this,
                Invocation.method(#safeApiCall, [apiCall]),
              ),
            ),
          )
          as _i5.Future<_i7.BaseResponse<T>>);
}
